export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';

/****** FETCH CONVERSATIONS ******/
export const FETCH_CONVERSATIONS_START = 'FETCH_CONVERSATIONS_START';
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_FAIL = 'FETCH_CONVERSATIONS_FAIL';

/****** FETCH MESSAGES ******/
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

/****** FETCH MESSAGES ******/
export const SEND_MSSSAGE_START = 'SEND_MSSSAGE_START';
export const SEND_MSSSAGE_SUCCESS = 'SEND_MSSSAGE_SUCCESS';
export const SEND_MSSSAGE_FAIL = 'SEND_MSSSAGE_FAIL';
